title: braindump(ag)
author: Andrei Gherzan

header_pages:
  - index.md
  - contact.md

style: dark

plugins:
  - jekyll-feed
  - jekyll-seo-tag

twitter:
  username: agherzan

permalink: /:categories/:title/
